### ISSUE TITLE
⚙️ CI/CDでのテスト実行を有効化

### ISSUE THREAD

**Issue by raijinb8** [raijinb8/magiq#93]
## 問題の説明
現在、GitHub Actions CI/CDパイプラインでフロントエンドとバックエンドのテストが一時的に無効化されています。テスト環境の問題が解決された後、CI/CDでのテスト実行を有効化する必要があります。

## 現在の状況
```yaml
# 現在（無効化中）
# - name: Run frontend tests
#   working-directory: ./frontend  
#   run: npm run test:run

# - name: Run Supabase Functions tests
#   run:  < /dev/null | 
#     cd supabase/functions
#     deno test --import-map ../import_map.test.json
```

## 受け入れ条件
- [ ] フロントエンドテストがCI/CDで実行される
- [ ] バックエンドテストがCI/CDで実行される
- [ ] テスト失敗時にPRマージが阻止される
- [ ] カバレッジレポートが生成される
- [ ] 複数のPRで並列実行が安定する

### 1. フロントエンドテスト有効化
```yaml
- name: Run frontend tests
  working-directory: ./frontend
  run: npm run test:run

- name: Run frontend tests with coverage  
  working-directory: ./frontend
  run: npm run test:coverage:ci

- name: Check coverage thresholds
  working-directory: ./frontend
  run: npm run test:coverage:check
```

### 2. バックエンドテスト有効化
```yaml
- name: Run Supabase Functions tests
  run: |
    cd supabase/functions
    deno test --import-map ../import_map.test.json

- name: Generate backend coverage
  run: |
    cd supabase/functions  
    deno test --import-map ../import_map.test.json --coverage=coverage
    deno coverage coverage --lcov > coverage.lcov
```

### 3. カバレッジ統合
- [ ] フロントエンドとバックエンドのカバレッジ統合
- [ ] Codecov連携の設定
- [ ] PRコメントでのカバレッジ表示

### 4. 品質ゲート設定
- [ ] カバレッジ閾値: 80%以上
- [ ] テスト実行時間: 5分以内
- [ ] 並列実行の安定性確保

## 依存関係
- **Depends on**: #90 (Docker権限問題の解決)
- **Depends on**: #91 (フロントエンドテスト実装)  
- **Depends on**: #92 (バックエンドテスト実装)

## 検証項目
- [ ] 新しいPRでテストが自動実行される
- [ ] テスト失敗時にマージができない
- [ ] カバレッジが正しく表示される
- [ ] 実行時間が適切な範囲内

## 優先度
**Medium** - 他のissue完了後に実施

## 関連
- Parent Issue: #63 (Epic: テスト環境の構築とCI/CD統合)

## ラベル
`enhancement`, `ci-cd`, `github-actions`, `testing`
